config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:"home#index"
  get "/bienvenida", to: "home#index"
  get "organizations", to: "organizations#index"
  get "organizations/new", to: "organizations#new", as: :new_organizations
  get "organizations/:id", to: "organizations#show"
  get "organizations/:id/edit", to: "organizations#edit"
  patch "organizations/:id", to: "organizations#update", as: :organization
  delete "organizations/:id", to: "organizations#destroy"
  post "organizations", to: "organizations#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_rich_text :description 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
    before_action :find_organization, except:[:new,:create,:index]
    before_action :authenticate_user!,  except:[:index,:show]
    def index
        @organizations = Organization.all
    end

    def new
        @organization = Organization.new
    end

    def create
        @organization = Organization.create(name:params[:organization][:name],description:params[:organization][:description])
        redirect_to organizations_path
    end

    def update
        @organization.update(name:params[:organization][:name],description:params[:organization][:description])
        redirect_to @organization
    end

    def destroy
        @organization.destroy
        redirect_to root_path
    end

    def show
    end
    def edit
    end
    def find_organization
        @organization = Organization.find(params[:id])

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<div class="large-container center-block">
    <h1>
        Hola  <%= current_user.email %>
    </h1>
<div>
    <%=link_to "Inicio", root_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GTeam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    </head>

  <body>
    <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%=render "partials/nav"%>
    <%= yield %>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: @organization, local:true) do |form| %>

    <div class="field">
    <%=form.label :name %>
    <%=form.text_field :name %>
    </div>

    <div class="field">
    <%=form.label :description %>
    <%=form.rich_text_area :description %>
    </div>

    <div >
    <%=form.submit %>
    </div>

<%end%>

app/views/organizations/_organization.html.erb
<div class="card" style="padding margin-top">
    <h3 class="text-uppercase"> <%= organization.name %> </h3>
    <p class="text-secondary"> <%= organization.description %>  </p>
    <%= link_to "Ver Mas", organization %>
</div>

app/views/organizations/edit.html.erb
<div class="small-container center-block">
    <%= render "organizations/form" %>
</div>

app/views/organizations/index.html.erb
<div class="large-container center-block">
    <h1>Lista de Organizaciones</h1>
    <%= render @organizations %>
</div>

app/views/organizations/new.html.erb
<div class="small-container center-block">
    <%= render "organizations/form" %>
</div>

app/views/organizations/show.html.erb
<div class="small-container center-block">
   <h1> <%=@organization.name %></h1>
    <div>
        <%=@organization.description %>
    </div>
    <div>
        <%=link_to "Eliminar el organizacion", @organization, method: :delete %>
    </div>
</div>   

app/views/partials/_nav.html.erb
<nav class="nav bg-light padding">
    <li class="nav-item">
        <%= link_to "Inicio", root_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Organizaciones", organizations_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "New", new_organizations_path, class:"nav-link" %>
    </li>
    <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Cerrar Sesion", destroy_user_session_path,method: :delete, class:"nav-link" %>
        </li>
    <% else %>
        <li class="nav-item">
            <%= link_to "Iniciar Sesion", new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Registrarse", new_user_registration_path, class:"nav-link" %>
        </li>
    <% end %>
</nav>